manifest:
  remotes:
    - name: alexandregressier
      url-base: https://github.com/alexandregressier
  projects:
    - name: zmk
      remote: alexandregressier
      revision: alexandregressier
      import: app/west.yml
  self:
    path: config
